### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wen-carl** [lihangleo2/mPro#1]
在viewpager界面多滑动几页，返回就会crash；
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.leo.myactivityoptions.MainActivity$2.onMapSharedElements(MainActivity.java:102)

**Comment by lihangleo2** [comment]
感谢提醒、代码更新过一次。现在的102行是空格。看看还会吗

**Comment by sundxing** [comment]
还是有的 
原因：在后台的话ViewHoder不会bind,所以滑动超过已经bind的范围就会找不到。
解决方案:  文章后面 https://android.jlelse.eu/dynamic-shared-element-transition-23428f62a2af
