### ISSUE TITLE
共享元素浏览大图卡顿

### ISSUE THREAD

**Issue by Krics1023** [lihangleo2/mPro#3]
首先十分感谢作者的demo,我就是参考了作者的demo才实现了如此好看的效果。
然后我想问一下，在数据源少的情况下，动画衔接的很顺畅。
但是一旦数据源增多，放大的时候还是很顺畅。可缩小返回的时候图片会卡在上一个页面中间一小会。这种是什么情况？
求解答，搜遍了网上，好像他们都没有遇到这个问题

**Comment by lihangleo2** [comment]
有些手机共享元素imageView对应TextView这种不同元素动画都很自然，但是有些手机会卡顿。你看看是不是这个问题。你是用我的demo也有这样的情况吗？如果是，我抽时间把bug修复下
