### ISSUE TITLE
viewpager切换至recyclerview不可见的item时返回闪退

### ISSUE THREAD

**Issue by JesseeChen** [lihangleo2/mPro#4]
1.当前recyclerview显示的item只有[1,2,3,4]
2.点击item1进入view pager，向左翻页至item0或向右翻页至item5(即切至recyclerview无对应共享元素的item)
3.点击返回闪退

ps:此bug可通过在onMapSharedElements里对view作判空规避掉,但效果不完美。google官方demo的做法是在transition动画开始之前调用recyclerview的scrollToPosition滑动至对应item。

**Comment by lihangleo2** [comment]
嗯，最近好多人提出来。我项目中的做法是在ViewPager滑动的时候，已经通过EventBus去通知ScrollToPosition了、但是不知道你们说的这个场景在我这，bug不会复现啊，能加个联系方式，帮我解决下吗
