### ISSUE TITLE
可以一对多吗？

### ISSUE THREAD

**Issue by ezfantasy** [lihangleo2/mPro#5]
例如RecyclerView的item和ViewPager的item 是对等共享的，总体上是多对多关系，现在我想问的是，我的第一个画面A上的ImageView只有一个，然后有另外一个RecyclerView去更新这个ImageView，然后点击这个ImageView还希望共享元素动画跳转到带有ViewPager的画面B，总体上是一对多关系，我尝试改造原来的多对多到一对多，遇到难题，求助下有什么好的办法吗？

**Comment by lihangleo2** [comment]
当然能改成一对多。我这里是列表对应列表。也可以是单个view对应单个view。总之来说可以1多1，1对多。多对1
